### ISSUE TITLE
More real estate on the mentoring view

### ISSUE THREAD

**Issue by Sir4ur0n** [exercism/website-copy#1067]
Hi,

Could we please increase (or make it scale) the mentoring view?

Currently about half of my screen is unused, yet I have an horizontal scroll bar on the code part, and the commenting section is small...

![image](https://user-images.githubusercontent.com/1204125/58903225-24976a80-8705-11e9-96eb-a9733df4b24a.png)

**Comment by rpottsoh** [comment]
This issue might belong on exercism/exercism.
@ihid?

**Comment by iHiD** [comment]
Yeah. Please reopen there if there's not already an issue for this there (I suspect there is already an issue, as I've commented on this before, but I can't be sure)

**Comment by Sir4ur0n** [comment]
My bad for creating this issue, it's kinda hard to know in which repo to open an issue depending on the problem...

Anyway I found https://github.com/exercism/exercism/issues/4735 which seems to be the same thing, cheers!
