### ISSUE TITLE
java: Create java-analyzer comments for the two-fer exercise

### ISSUE THREAD

**Issue by jmrunkle** [exercism/website-copy#1115]
I think it is wise at this point to create our customized comments for the two-fer exercise.

Should follow the pattern over in this PR: https://github.com/exercism/website-copy/pull/1009

Not everything will be perfect and that PR is the first one that will go in so we need to be tracking their progress / example.

NOTE: We may temporarily store them inside the java-analyzer REPO for convenience (which matches what some other analyzers have been doing).

**Comment by jmrunkle** [comment]
Taking a stab at this...

**Comment by iHiD** [comment]
@jmrunkle Which of these comments are the ones that go alongside approval (rather than disapproval)?

**Comment by jmrunkle** [comment]
Approval only comments moved over to #1139, this one can wait until we decide if we are doing disapprove comments.
