### ISSUE TITLE
Link broken on  https://exercism.io/tracks/rust/tests

### ISSUE THREAD

**Issue by dkotrada** [exercism/website-copy#1175]
In 'Writing Code' section is this linkk broken -> 'chapter on modules'

**Comment by rahulkeerthi** [comment]
Correct link is [here](https://doc.rust-lang.org/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html) but I can't find the page in the repo...

**Comment by corneliusroemer** [comment]
@coriolinus Can this issue be closed now that the PR is merged?

**Comment by angelikatyborska** [comment]
Fixed in https://github.com/exercism/rust/pull/949
