### ISSUE TITLE
Preview of comment - on edit

### ISSUE THREAD

**Issue by marauderlabs** [exercism/website-copy#1234]
No 'Preview' window available to preview the current comment as we edit it. It's only available for new comments

**Comment by marauderlabs** [comment]
No 'Preview' window available to preview the current comment as we edit it. It's only available for new comments

**Comment by corneliusroemer** [comment]
@ihid Misclassified issue: Belongs to main repo https://github.com/exercism/exercism

**Comment by iHiD** [comment]
I think this got fixed.
