### ISSUE TITLE
issue template: provide one that suggests "tagging" the title

### ISSUE THREAD

**Issue by NobbZ** [exercism/website-copy#1250]
Please provide an issue/PR template that asks to tag the title accordingly.

This repository has a lot of subtopics. And those even split further into tracks, such that there are a lot of responsibilities divided through out the repository.

Often titles of PRs and issues are poorly choosen and its hard to know wether or not its related to an individual or team.

Therefore I suggest an issue template that asks the creator to provide a proper title and description.

* Issues and PRs that are for mentornotes should be "tagged" by track and exercise, eg: `mentornotes/javascript/hello-world: add notes", `mentornotes/erlang/two-fer: fix typo`
* Issues and PRs that are for mentor bios should be tagged by track at least, eg: `bio/javascript: add myself`, `bio/ruby: fix avatar of foomtor`, `bio/python: add ham and eggs to description of PyBaker`
* Issues and PRs that are for analyzer comments should also contain track and exercise, eg: `analyzer/elixir/two-fer: create comments`

Perhaps there are further sub projects which need additional tagging.

Exact tags to use and which sub projects need their own is subject to discussion, above are just examples.

As part of this, I'd also suggest to add more codeowners as necessary for the analyzer, mentor bios, etc, as soon as we know more details about #1249.

**Comment by NobbZ** [comment]
After #1277 has been merged and at least should tag PRs by their type, we should ask our self, whether or not we also want to tag by language.

Though this would require us to add ~50 labels for the languages and to give them colors.

If this tagging works in an automated way, reviewers should be able to easily filter things they are responsible for.

My original proposal also included to have the exercise "tagged", but as it was about the subject, rather than github labels, I think we can just ask for the discipline to mention it in the subject (if it applies).

I'd like to discuss whether or not we create labels for the languages before I create a PR with the actual labeller.

**Comment by iHiD** [comment]
> Though this would require us to add ~50 labels for the languages and to give them colors.

I believe @kytrinyx could script this, and they can all be the same colour I think.

So the question I'm unsure of here is whether we want to use issue templates or whether we're using GitHub actions? Or whether we're using a mixture? And if the mixture, how they interact/overlap?

As a side note, in case you didn't know, you are able to PR issue templates. See [automated-analysis repo](https://github.com/exercism/automated-analysis/tree/master/.github/ISSUE_TEMPLATE) for examples.

**Comment by NobbZ** [comment]
Yeah, I do know I could do that, though I hoped I could kick off some discussion first…

**Comment by kytrinyx** [comment]
I can script the labels, no problem.

I would _much_ prefer to use automation over issue templates.

It looks like what we care about is:

- what language
- what part of the copy are we changing

Both of these are automatable based on the file tree.

Am I missing something?

**Comment by iHiD** [comment]
As an extra piece of information, we'll soon be removing mentor bios from this repo, which should reduce a lot of the noice.

**Comment by NobbZ** [comment]
> Am I missing something?

No, I don't think you miss anything.

I've also already found an action that enables us to manage the labels through the repository: [`lannonbr/issue-label-manager-action`](https://github.com/lannonbr/issue-label-manager-action)

I do not have any clue though what way were the best to assign the colors. Or would we just make them all the same?

Anyway, assigning a label based on the touched path(es) should be trivial as soon as we have the labels in place.

> As an extra piece of information, we'll soon be removing mentor bios from this repo

Oh, where will they go? Anyway, its a change I'm looking forward to.

**Comment by iHiD** [comment]
> Oh, where will they go? Anyway, its a change I'm looking forward to.

Directly into the website as part of our step towards better mentor onboarding, and also proper mentor "profiles" on the site that mentors can customise to showcase their work (e.g. show off some testimonials etc)

**Comment by kytrinyx** [comment]
> I've also already found an action that enables us to manage the labels through the repository

For now it's easier to just script the labels, thanks!

> I do not have any clue though what way were the best to assign the colors.

I'm using just one color, as these labels are all one category of thing.

I'll do this now.

**Comment by kytrinyx** [comment]
Ok, the labels are made. I'll leave you all to sort out the GitHub Action to label issues based on track (the labels are named `track/$TRACK_ID`, where $TRACK_ID corresponds to the repo name of the track).

**Comment by NobbZ** [comment]
:+1: I've added PR #1281 which should cause labelling of future PRs by their target track as soon as it got merged.

**Comment by angelikatyborska** [comment]
The labeler has been added in https://github.com/exercism/website-copy/pull/1858

PS: Older PRs might not be labelled at the moment due to an incident where all labels were accidentally removed from this repository. I will try to add them back manually, but the labeler works for sure :)

I believe that means this issue can be closed.
