### ISSUE TITLE
labeler does not work correctly

### ISSUE THREAD

**Issue by NobbZ** [exercism/website-copy#1284]
I provided PRs #1277 and #1281 to automatically label PRs.

Due to a limitation in the action (actions/labeler#12) it seems we are unable to actually read the configuration for the action, when the PR is created from a fork…

I'll dig a bit deeper during the next days to figure out how to solve this, as the solution given in the linked ticket doesn't seem to actually work (creating a cron job, rather than triggering on PRs) as a cron triggered job hasn't the necessary information about PRs.

**Comment by angelikatyborska** [comment]
I believe this is no longer a problem. For example PR https://github.com/exercism/website-copy/pull/1945 was created from a fork, and the labeler added labels.

Please reopen if I'm mistaken!
