### ISSUE TITLE
what about the upgrade process of cli v2 to latest

### ISSUE THREAD

**Issue by SeasonLeee** [exercism/website-copy#1390]
Hi everyone, thanks for the awesome project! And I am so grateful years ago when I used it to practice my Java skill with the help of this great magical thing!

But I didn't continue the exercises because there's something happened in my life, and lately I want to pick up my Java skill and I remember this. 

To my delight, the whole project is upgraded! Good job!

Although, when I tried to upgrade cli, I only found the instructions for v1 to v2... what about v2 to latest? Is it just simply `exercism --upgrade` ?

Or is it just simpler that I might just uninstall the old one and reinstall it?

Thanks in advance for your advice😊

**Comment by NobbZ** [comment]
No, `exercism --upgrade` will not work, as there was a bug in older upgrade code, that only got fixed with 3.0.5ish…

The probably easiest way to update is to remove the old version by the means of the original installation and reinstalling the most recent version as described in the guide.

**Comment by SeasonLeee** [comment]
@NobbZ Thank you so much! I took your advice and uninstalled it and reinstall it with homebrew, now I can happily exercising my coding😆 Thank you!
