### ISSUE TITLE
Typo in JavaScript track's Raindrops test

### ISSUE THREAD

**Issue by evanslaton** [exercism/website-copy#1398]
Lines 36 - 40 in raindrops.spec.js:
`test('the sound for 27 is Pling as it has a factor 3', () =>
    expect(convert(35)).toEqual('PlangPlong'));

test('the sound for 35 is PlangPlong as it has factors 5 and 7', () =>
    expect(convert(35)).toEqual('PlangPlong'));`

Line 37 should be:
`expect(convert(27)).toEqual('Pling'));

**Comment by aimorris** [comment]
Don't know when, but has been fixed.

**Comment by yawpitch** [comment]
Closing as this was fixed by exercism/javascript#836, you must have an older copy of the test.
