### ISSUE TITLE
Go: Include golint in setup instructions

### ISSUE THREAD

**Issue by jjshanks** [exercism/website-copy#1413]
There was a discussion on slack about how `golint` is considered a standard and many mentors require solutions to pass `golint` prior to approving. If the exercism mentors on the go track are going to require a tool that requires additional setup it should be documented in setup and include usage.

**Comment by angelikatyborska** [comment]
Setup up instructions (how to install the language and necessary tools, how to run tests) are part of the track repositories, e.g. https://github.com/exercism/go/blob/main/docs/INSTALLATION.md and https://github.com/exercism/go/blob/main/docs/TESTS.md

I would recommend opening an issue in the `exercism/go` repository instead to talk about `golint`.
