### ISSUE TITLE
Go: Review resources

### ISSUE THREAD

**Issue by jjshanks** [exercism/website-copy#1414]
The resources for the go track at https://exercism.io/tracks/go/resources don't appear to include references or details about `golint`. A recent discussion on slack showed that many mentors require solutions to pass `golint` before being approved because `golint` is considered a community standard. It would be useful to students have pointers to resources that reflect this standard.

**Comment by angelikatyborska** [comment]
The resources documents are part of the track repositories, for example: https://github.com/exercism/go/blob/main/docs/RESOURCES.md

I would recommend opening an issue in the `exercism/go` repository instead to talk about `golint`.
