### ISSUE TITLE
Rendering issue on configuration walkthrough

### ISSUE THREAD

**Issue by c-dante** [exercism/website-copy#160]
Seems that this didn't compile as expected. Here's the rendering I get:

https://github.com/exercism/website-copy/blob/e04726b06f51ab5948d68fff1809c0efe44089d5/walkthrough/index.html#L156

![image](https://user-images.githubusercontent.com/6332726/42717695-d73238ae-86d0-11e8-939c-31f5faaef012.png)

```
To have the exercism executable available everywhere on the command line you need to make sure ~/bin is in your $PATH.

There is a chance it’s there already; let’s see whether it is:

<a href="javascript:void(0)" data-passage=" &quot;:$PATH:&quot; == *&quot;:$HOME/bin:&quot;* "> ":$PATH:" == *":$HOME/bin:"* </a> && echo "~/bin is in PATH" || echo "~/bin is not in PATH"
If the above prints ~/bin is not in PATH let’s add ~/bin to $PATH and reload Bash configuration:
```

**Comment by sfairchild** [comment]
I think this has been fixed and can probably be closed

![exercism io_cli-walkthrough](https://user-images.githubusercontent.com/1839202/46556745-95a42b00-c8b5-11e8-8eb6-8a22459a1de4.png)

**Comment by kntsoriano** [comment]
@sfairchild Thanks for that! I forgot to close this :)

**Comment by bgrabow** [comment]
I am seeing this issue now. Maybe the latest changes (https://github.com/exercism/website-copy/commit/a20bf789c47d7e21be804c0b613d72160fdd7439) were not compiled correctly?

![screenshot from 2018-11-13 11-39-43_crop](https://user-images.githubusercontent.com/5761437/48432120-18cc6280-e739-11e8-9d1f-8fe711ac87fa.png)

**Comment by kntsoriano** [comment]
@bgrabow Thanks for reporting this!

**Comment by bgrabow** [comment]
LGTM

**Comment by kntsoriano** [comment]
Thanks again for letting me know about the issue!
