### ISSUE TITLE
objective doesn't match test case - F# Hello World

### ISSUE THREAD

**Issue by complexzeros** [exercism/website-copy#1615]
The [Hello World F# Exercise](https://exercism.io/my/solutions/e3a4b5294a044c928beaca92ed539f88) Says to 'Write a function that returns the string "Hello, World!".', but the test case expects a simple value, not a function.

**Comment by NobbZ** [comment]
The link you have pasted is not accessible for anyone but you.

Could you please copy and paste relevant sections of descriptions or perhaps link to corresponding places in the repository for F# exercises?

Though I have to say, READMEs are written in a way that is mostly language agnostic, and therefore "function" is the term that is most appropriate through *all* languages.

**Comment by complexzeros** [comment]
From the Instructions:

> The classical introductory exercise. Just say "Hello, World!".
>
> "Hello, World!" is the traditional first program for beginning programming in a new language or environment.
>
>The objectives are simple:
>
>**Write a function** that returns the string "Hello, World!".
>Run the test suite and make sure that it succeeds.
>Submit your solution and check it at the website.

And the unit test:
```
[<Fact>]
let ``Say Hi!`` () =
    hello |> should equal "Hello, World!"
```

That said, I doubt this would actually trip someone up. (Just caused me a moment of confusion as a beginner.) And it doesn't seem worth changing if the same text is used for other languages.
