### ISSUE TITLE
Fix typo and wording in Dart track description

### ISSUE THREAD

**Issue by Cal-Hagner** [exercism/website-copy#1617]
Currently, the description of dart reads:

"Dart brings object-oriented and typing together with the flexibility that JavaScript is known for. It is designed to simplify common programming tasks. In recent years, it's popularity amongst the software development community has grown tremendously."

The typo is "it's popularity", which should be corrected to "its popularity" to properly form the possessive.

Wording change is to replace "amongst" with "in", as in is both more common and more proper English.

**Comment by Cal-Hagner** [comment]
I poked around in the file structure of this site, and I am, to put it mildly, confounded as to where to find the content that needs to be edited for this issue. If someone could explain to me the file structure, I would be happy to resolve this issue myself. Thank you!

**Comment by rahulkeerthi** [comment]
Hi @Cal-Hagner - thanks for offering to help. The repo you're looking for is [here](https://github.com/exercism/dart/tree/master/docs). Exercism maintains separate repos for each language track - you can search for them from here, or see the whole list using the [exercism-track tag](https://github.com/search?q=topic%3Aexercism-track+org%3Aexercism+fork%3Atrue).

Let me know if you have any trouble finding the doc or making the PR.
