### ISSUE TITLE
License pages linked to from onboarding page should have license text

### ISSUE THREAD

**Issue by C-Saunders** [exercism/website-copy#165]
The [MIT](https://exercism.io/licences/mit) and [CC-BY-SA-4.0](https://exercism.io/licences/cc-sa-4) pages do not have the license text on them right now.

I think, based on [this part](https://github.com/exercism/website/blob/master/app/controllers/pages_controller.rb#L32) of the website code, that the `pages_controller` is looking for these in the "pages" directory of this repo, but the license markdown files are in the "licenses" folder instead.

I am happy to make a PR to move those files into the "pages" directory, but I wasn't sure if it would be better to adjust things on the website side instead.

**Comment by iHiD** [comment]
Thanks. Yeah - this seems to be a bug! We'll fix it in website. Thanks.
