### ISSUE TITLE
typo on exercism.io/mentor/registrations/new

### ISSUE THREAD

**Issue by jamessouth** [exercism/website-copy#1674]
Hello, I didn't see where I could directly edit [https://exercism.io/mentor/registrations/new](https://exercism.io/mentor/registrations/new) via PR to change `line` to `like`:

(from the page)
Your language

Mentors can help on as many tracks as they **line**, but we ask that people choose one to get started with in order to familiarise yourself with the process.

Thank you!

**Comment by yawpitch** [comment]
Hi James, turns out this was actually in another repo, but thanks for the find! Closing this one as it will be fixed by exercism/website#983 ... if I can keep that one open long enough to get merged around the Hacktoberfest spam assassin script! :-)
