### ISSUE TITLE
External link to source of Robots has changed

### ISSUE THREAD

**Issue by MylesLandais** [exercism/website-copy#1745]
Website not longer appears to be owned/registered to paul, suggesting this link be removed or replaced.

found under Language tracks / TypeScript / Robot Name

```
Source
A debugging session with Paul Blackwell at gSchool. http://gschool.it
```

**Comment by kotp** [comment]
@MylesLandais, are you up for a pull request to remove it?

**Comment by MylesLandais** [comment]
Meged in pull request here https://github.com/exercism/typescript/pull/342

**Comment by kotp** [comment]
Thank you @MylesLandais
