### ISSUE TITLE
cli.exercism.io/usage api_key should be token

### ISSUE THREAD

**Issue by stevensonmt** [exercism/website-copy#180]
Current text on the site reads:
```
exercism configure --key=YOUR\_API\_KEY
```
but the cli flag is actually `--token=` and the account settings page presents it as `CLI token`, so the site should be edited to read:
```
exercism configure --token=YOUR\CLI\TOKEN
```

**Comment by iHiD** [comment]
Nice catch. Mind opening a PR for this too pls? You can edit the file directly on Github to do that :)

**Comment by stevensonmt** [comment]
Sure, I just wasn't sure if that part of the site was getting a complete behind the scenes rewrite that I don't have access to.

**Comment by iHiD** [comment]
The CLI site is here: https://github.com/exercism/cli.exercism.io/

**Comment by stevensonmt** [comment]
it looks like the page I was using now redirects to exercism.io/cli/ which uses the correct terms. This issue and the other are likely moot.
