### ISSUE TITLE
cli.exercism.io/troubleshooting debug should be troubleshoot

### ISSUE THREAD

**Issue by stevensonmt** [exercism/website-copy#182]
Text from the site reads:

>If you are still having trouble open an issue in exercism/cli on GitHub with the output of the debug command.
>```
>exercism debug
>```
however the cli does not recognize `debug` and instead uses `troubleshoot` as the command for this function.

**Comment by iHiD** [comment]
Mind opening a PR for this pls? You can edit the file directly on Github to do that :)
