### ISSUE TITLE
Correction for the "Running the Tests" page example

### ISSUE THREAD

**Issue by jurgengjoncari** [exercism/website-copy#1868]
In the [Running the Tests](https://exercism.io/tracks/python/tests) page
Under _**PEP8**_ section
In the `pytest --pep8 bob_test.py` example, it is used the "bob_test.py" which is the test file
Instead it should be used the "bob.py" file
As it is the exercise that the user wants to test for compliance to the style

**Comment by kotp** [comment]
This might belong under exercism/python instead. 

/cc @exercism/python

**Comment by angelikatyborska** [comment]
The page has been rewritten completely and the feedback doesn't apply anymore because any commands with the `--pep8` flag were removed from examples. I'll close this.
