### ISSUE TITLE
Visualise "Explore ... community solutions" by clusters

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/website-copy#187]
Hello!

As both a mentor, and learner, I find the current [`.../exercises/.../solutions/` pages](https://exercism.io/tracks/python/exercises/space-age/solutions) a bit strange. The solutions are ordered by number of comments, right?

I'm not sure whether sorting by likes, loves or geniuses is better, and would therefore like to suggest a clustering approach. Many solutions are similar, so it doesn't really matter whose version I select. I feel that the most instructive comparison is the one between differently _structured_ solutions. Might these different structures be determined automatically somehow?

If yes, how about some kind of [iPhoto-like visualisation](https://images.apple.com/ca/ilife/iphoto/images/laptop_gallery_04_20111018.jpg) of the "solution approaches" then? With one thumbnail per cluster that highlights that structure's main features (and maybe the comment, like, etc. stats of all individual solutions in that group summed up). And the thumbnails could be aligned like on a Pinterest-board: longer and shorter code-thumbnails tiled.

That latter display style could be used even without clustering, as an MVP so to speak for more informative solutions pages.

What do you think? Are there any other plans to update those pages?

**Comment by iHiD** [comment]
Would you mind moving this to exercism/exercism.io ? It'll get proper discussion there.

**Comment by katrinleinweber** [comment]
OK, thanks for the hint! https://github.com/exercism/exercism.io/issues/4067
