### ISSUE TITLE
Typo on research frontpage

### ISSUE THREAD

**Issue by mogggy** [exercism/website-copy#1879]
`eligable` => `eligible`

Under "Eligibility and time commitment" subheading
"Anyone is eligable to take part."

Sorry I couldn't find the page on github to do it myself.

**Comment by angelikatyborska** [comment]
The offending line of code can be found here: https://github.com/exercism/v2-website/blob/fb6555b3376c724671f15ad5be5ffbe90995edd6/app/views/research/experiments/show.html.haml#L42

I believe it is too late to fix it since the v2 website is no longer getting updated and everyone is working on v3.

**Comment by kotp** [comment]
Closing this issue from v2.
