### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by astroparam** [exercism/website-copy#1994]
These links are broken:

https://github.com/exercism/website-copy/blame/3aa4a31dc850e545cc2aadb073a0484ed0ad7be8/pages/become_a_maintainer.md#L146-L148

https://github.com/exercism/website-copy/blame/3aa4a31dc850e545cc2aadb073a0484ed0ad7be8/pages/become_a_maintainer.md#L151

These links belongs to [legacy docs](https://github.com/exercism/legacy-docs) repo.

**Comment by angelikatyborska** [comment]
@iHiD I think your attention is warranted here, the mentioned broken links are live at https://exercism.io/become-a-maintainer

**Comment by iHiD** [comment]
Thanks.

@astroparam Want to PR to point them to the correct repo?

**Comment by astroparam** [comment]
@iHiD Sure
