### ISSUE TITLE
Mentor queues frozen.

### ISSUE THREAD

**Issue by ak4ra** [exercism/website-copy#2003]
Hello,

It's been around 80 days without a mentor reply in my C and Scheme tracks. I thought maybe it's a coincidence, but the mentor from the C track just replied to a C++ exercise I submitted 1-2 days ago, so I suppose something may be wrong.

I'm opening an issue as suggested in the FAQ, doesn't seem to be an open one on the matter at the moment.

**Comment by AKerr9509** [comment]
A similar thing is happening on my C track (~5 days w/o a queue update, no mentor reply).

**Comment by flexits** [comment]
Can confirm. It's being 5 days since I've uploaded a solution and no movement still...

**Comment by ak4ra** [comment]
I got a reply on the Scheme track a few days ago. Have not gotten one on the C track though, since 100 days ago. I guess it is possible this is not a bug and it is just that the mentors may have been less active lately, but I can't tell for sure.

**Comment by angelikatyborska** [comment]
@ak4ra The C mentors are doing their best but there's simply not enough of them. Your solution is in the queue and mentors can see them. If you know any experienced C developers, it would be great if you could ask them to join as C mentors on Exercism, or maybe you yourself already have enough experience to help out with mentoring the easier exercises?

**Comment by ak4ra** [comment]
Thanks. I'm not in a hurry, I just thought it may have been some kind of bug, based on what I read in the FAQ.

I like the idea of mentoring, though probably not in the C track, but it may be better to wait until I have some more experience before that.

I will close the issue then.
