### ISSUE TITLE
Go Track - Landing Page - end of sentence on tile

### ISSUE THREAD

**Issue by NickFoden** [exercism/website-copy#2067]
Desc:
- missing end of sentence on tile "Your favorite feature may be . . . "
- https://exercism.org/tracks/go

![image](https://user-images.githubusercontent.com/8321838/132718092-eb7d5937-f11a-4996-b3ed-71637d467e96.png)

**Comment by angelikatyborska** [comment]
This is a CSS bug, it's not specific to go. It was already reported in a different repository during the beta phase: https://github.com/exercism/v3-beta/issues/181 

@iHiD that's another duplicate from v3-beta

**Comment by NickFoden** [comment]
Ah ok thanks for the heads up. I will close this one then. v3 is looking sharp and performing well for me !
