### ISSUE TITLE
Docs Typo - Misspelling "experince"

### ISSUE THREAD

**Issue by peterloane** [exercism/website-copy#2076]
Hi
Misspelling here
https://exercism.org/docs/tracks/go

Reads
"make the most of your Go experince on Exercism,"

experince should be experience 

Regards 

Peter

**Comment by angelikatyborska** [comment]
Thanks! This is an issue with all docs pages, not just for Go. The offending line of code is in a different repository. I opened a PR that should fix this: https://github.com/exercism/website/pull/1948
