### ISSUE TITLE
Docs:Mentoring intro - Missing bullet

### ISSUE THREAD

**Issue by peterloane** [exercism/website-copy#2078]
Mentoring intro page
https://exercism.org/docs/mentoring
Contains bullets linking to  2 of 3 page links in lefthand pane

Reads like a bullet link to 
https://exercism.org/docs/mentoring/markdown 

is missing

**Comment by IsaacG** [comment]
Requested https://github.com/exercism/docs/pull/267

**Comment by ErikSchierboom** [comment]
Closed by https://github.com/exercism/docs/pull/267
