### ISSUE TITLE
Updates: exercism.org

### ISSUE THREAD

**Issue by peterloane** [exercism/website-copy#2083]
1: On https://exercism.org/ intro it reads
"Get really good at programming. Develop fluency in over 55 programming languages..."

Then in the next section the heading is "Explore and get fluent in 55 programming languages" (Not "in over 55...")

There are exactly 55 tracks so should the "over" be removed?

On https://exercism.org/about there is a misspelling

We rely on open-source contributions and cash donations to achieve our mission. Can you **space** some time or money to support our mission?

Should read

We rely on open-source contributions and cash donations to achieve our mission. Can you **spare** some time or money to support our mission?

**Comment by IsaacG** [comment]
The first number is hard coded. The second is a macro that expands to the exact track count. I removed "over".

**Comment by peterloane** [comment]
Cool.

**Comment by peterloane** [comment]
Closed after updates.
