### ISSUE TITLE
analysis of submitted exercise takes unusually long (_still processing_)

### ISSUE THREAD

**Issue by matari-dev** [exercism/website-copy#2252]
Please see image.
I submitted the exercise twenty hours ago and the Exercism website says it is still analysing when the page says estimated time to completion of analysis is 10 to 30 seconds.

Please let me know if you need any additional information.  
Thanks!  

![my submitted exercise still under analysis after 20 hours](https://i.imgur.com/eFKpJrv.png)

**Comment by IsaacG** [comment]
For Exercism support, please use [the forum](https://forum.exercism.org/).

This particular issue [was discussed here](https://forum.exercism.org/t/stuck-in-processing/4338/8).

**Comment by matari-dev** [comment]
copy that, thank you IsaacG 👍
