### ISSUE TITLE
Add a CLI upgrade section to FAQ page for supporting users

### ISSUE THREAD

**Issue by nywilken** [exercism/website-copy#261]
This requests stems from an open issue on the CLI https://github.com/exercism/cli/issues/680#issuecomment-407901702

**Comment by iHiD** [comment]
I think what you're looking for exists at exercism.io/faqs - feel free to submit Pull Requests for extra sections there. that would be very appreciated. You can edit the file in this repo to submit the Pull Request :)

**Comment by nywilken** [comment]
Thanks @iHiD. I updated the issue so that it is specific to adding an CLI upgrade section.

**Comment by nywilken** [comment]
Sorry for the open close. I’ll work on adding the section and submitting the PR.

**Comment by nywilken** [comment]
@iHiD I missed the boat on #254, but I did start to compile some key items specific to upgrading the CLI and not so much the problems pertaining to the migration. You can assign this issue to me. I will open a PR with some proposed FAQs in the morning (EST)

**Comment by rpottsoh** [comment]
I am presuming that #417 addressed this issue.

**Comment by nywilken** [comment]
@rpottsoh PR #417 addressed this issue thanks for closing.
