### ISSUE TITLE
Every solution was Published 28 days ago

### ISSUE THREAD

**Issue by ricardomatias** [exercism/website-copy#314]
I see this behavior in all my exercises.

![exercism-bug](https://user-images.githubusercontent.com/8850708/43948417-0db7a7e0-9c8b-11e8-9251-870f01a42265.png)

**Comment by NobbZ** [comment]
This is working as expected unless one of those solutions was acutally only published after the release of v2.

**Comment by iHiD** [comment]
Closing as duplicate of https://github.com/exercism/exercism/issues/4073
