### ISSUE TITLE
/getting-started page: numbered lists restart in each section

### ISSUE THREAD

**Issue by jonathansewell** [exercism/website-copy#342]
The copy says "see step 8" but the numbered lists restart under each heading, so there is no step 8.

Screenshot from https://exercism.io/getting-started

<img width="774" alt="screen shot 2018-08-13 at 22 29 34" src="https://user-images.githubusercontent.com/286782/44056392-66276b1c-9f48-11e8-97e0-ba9d0924ce5d.png">

**Comment by iHiD** [comment]
Thanks. Any chance you could raise a PR this pls?

**Comment by jonathansewell** [comment]
Yes I'll open a PR. 

I'm not sure which markdown flavor is used to generate the website. It's different from GitHub's (the numbering is as expected in GitHub's markdown preview but not on the website).

Maybe I'll just change the copy to say "see step 1 above"
