### ISSUE TITLE
Javascript Mentored Track - Hello World

### ISSUE THREAD

**Issue by ahmadshahrour951** [exercism/website-copy#368]
So being a new member here, I just entered the javascript track and I tried starting the 'Hello World' core track. Its grey and unclickable, not sure why - i.e. I can't start...

<img width="1213" alt="Screen Shot" src="https://user-images.githubusercontent.com/33921028/44348076-89e9da00-a4aa-11e8-93a6-0c5e8253a297.png">

**Comment by iHiD** [comment]
@ahmadshahrour951 Is this fixed for you now?

**Comment by ahmadshahrour951** [comment]
@iHiD Works just fine! thank you so much for the fix!

**Comment by iHiD** [comment]
Great. Sorry you had the problem and thanks for reporting.
