### ISSUE TITLE
Review of submission is listed in Dashboard as "Requires Action" despite lack of updates

### ISSUE THREAD

**Issue by jeffdparker** [exercism/website-copy#399]
I reviewed submission

    https://exercism.io/mentor/solutions/e659f656d83242a0a1d73688c6ce805f

and asked for revs.  Student replied, agreed to refactor, but has not resubmitted.
The submission is listed in my Dashboard under the Requires Action label.

Additional Information: I've been away from Exercism for about 10 days: I may have missed something that was entered and deleted.

- Jeff Parker

**Comment by NobbZ** [comment]
That basically means, that the student did the last action, he commented or submitted something. If he really only said that he will look into it, you can wait a while and then ping him by commenting again and ask him if he made any progress or has problems he can't solve or just has forgotten to submit…

If he opted in, he will receive an email notifying him about you having commented, or if he opted out, that solution is in "requires actioon from student" now…

**Comment by jeffdparker** [comment]
I've seen many cases such as the one you describe.  They don't appear in my
dashboard.

Two cases like this do appear in my dashboard as actions requiring my
attention.  I believe that to be an error: the system doesn't show me
anything to pay attention to.

I'm not looking for work - I'm just trying to identify something that may
be a bug.

- Jeff Parker

**Comment by rpottsoh** [comment]
@jeffdparker are you still experiencing the original symptom that you reported back on August 28th?

**Comment by jeffdparker** [comment]
I have learned to live with it.

If you approve a student's problem, and (s)he replies, that counted as
something you need to react to.  I learned to ignore it.

- jdp

**Comment by rpottsoh** [comment]
I'll move it

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism #4449](https://github.com/exercism/exercism/issues/4449) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism #4448](https://github.com/exercism/exercism/issues/4448) via [**ZenHub**](https://www.zenhub.com/)

**Comment by iHiD** [comment]
Thank you!
