### ISSUE TITLE
Broken link to README generation on become-a-maintainer

### ISSUE THREAD

**Issue by Mavelous** [exercism/website-copy#429]
Text in the page says:

> The READMEs are generated, and all the details are explained here.

With the "here" being a link to https://exercism.io/language-tracks/exercises/anatomy/readmes.md, which is a 404.

**Comment by iHiD** [comment]
Which page?

**Comment by Mavelous** [comment]
Sorry.  https://exercism.io/become-a-maintainer

**Comment by iHiD** [comment]
@kytrinyx Do you know where that content is/was?

**Comment by kytrinyx** [comment]
oh uh yeah... it's on my list this month to rearrange all of that, but it's a pretty big job and I've not gotten to it yet.

Is this what you're thinking of?

https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

**Comment by iHiD** [comment]
Magic. So I guess we need to either move that into website-copy or change the link to point people to GitHub?

**Comment by kytrinyx** [comment]
I think the link is just broken in the sense that it's probably missing a leading slash or something. I'll take a look.

**Comment by iHiD** [comment]
@kytrinyx The link is to the exercism website, not github, but those pages aren't on the website any more.

**Comment by kytrinyx** [comment]
@iHiD They never were on the website. This page was copied over from the docs repo.
