### ISSUE TITLE
broken links on the elm track resources page

### ISSUE THREAD

**Issue by Ferengee** [exercism/website-copy#442]
On the page https://exercism.io/tracks/elm/resources
the link 'More at the official language site.' points to a relative path, instead of to the real site

Some example links are broken, for example: http://elm-lang.org/examples/zip
which redirects to http://try.elm-lang.org/examples/zip which cannot be resolved.
This is not the fault of the exercism team but you might want to replace the links with something else or update the text. I just wanted to point out that they don't work atm.

**Comment by rpottsoh** [comment]
[RESOURCES.md](https://github.com/exercism/elm/blob/master/docs/RESOURCES.md) appears to have been updated since this issue was created.  @Ferengee if you are still experiencing the same issues please reopen this issue.  I am going to close and assume the issue has been resolved.
