### ISSUE TITLE
All the "/you-can-help/*.md" links are broken in become_a_maintainer.md

### ISSUE THREAD

**Issue by scottcrawford03** [exercism/website-copy#523]
When clicking on any link that is backed by a markdown file located in `you-can-help/`, the file does not exist.

ex. 
```
Triaging issues
A great issue is detailed and actionable. When they're not, you can help ask the questions to make them so.

For more detailed suggestions about things to keep in mind when triaging, check out this documentation.
```

when clicking on `this documentation` you are met with this screen:
<img width="1677" alt="the_page_you_were_looking_for_doesn_t_exist__404_" src="https://user-images.githubusercontent.com/8398867/47579020-e3daa600-d918-11e8-9b7c-368e22394f63.png">

when clicking on the link through github, you are met with the 404 page.

Is there a place where the files now live? If so I would be happy to update!

Cheers

**Comment by rpottsoh** [comment]
fixed by #480.
