### ISSUE TITLE
propose new test for Rakefile: First letter of name matches filename.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/website-copy#636]
It is easy to miss this check when manually checking mentor bio JSON updates.  Sometimes people grab the wrong file and sometimes those reviewing forget to check that the first letter of their name agrees with the name of the JSON file.

I would like to see a test added to Rakefile that will confirm that first letter and filename agree.

**Comment by iHiD** [comment]
Very good idea.

FYI. I'm toying with moving these bios directly into the website soon and giving mentors more control over their public profiles as a bigger set of changes around improving the mentor/learner interactions.

**Comment by iHiD** [comment]
@kytrinyx @rpottsoh Do either of you want to volunteer to add the test?

**Comment by rpottsoh** [comment]
#646 already in progress.

**Comment by iHiD** [comment]
Ah great. Thank you :) As I'm a :+1: on this conceptually, shall we close this issue?

**Comment by rpottsoh** [comment]
PR will close this.  But doesn't matter to me.
