### ISSUE TITLE
"I'll pass, thanks" is now "Leave conversation"

### ISSUE THREAD

**Issue by bitfield** [exercism/website-copy#659]
On the 'Mentoring workflow' page the references and screenshots to the "I'll pass, thanks" button need updating to "Leave conversation".

**Comment by rpottsoh** [comment]
[mentoring_workflow.md](https://github.com/exercism/website-copy/blob/master/pages/mentoring_workflow.md)

**Comment by rpottsoh** [comment]
cc: @iHiD 

I think this should be moved to exercism/exercism.

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism #4555](https://github.com/exercism/exercism/issues/4555) via [**ZenHub**](https://www.zenhub.com/)
