### ISSUE TITLE
/team/mentors pagination issue

### ISSUE THREAD

**Issue by Falci** [exercism/website-copy#664]
The [three](https://exercism.io/team/mentors?page=9) [last](https://exercism.io/team/mentors?page=10) [pages](https://exercism.io/team/mentors?page=11) of mentors seems to be wrong. The same mentor appear in all of them.

**Comment by rpottsoh** [comment]
Pages [10](https://exercism.io/team/mentors?page=10) and [11](https://exercism.io/team/mentors?page=11) are not needed.

cc: @iHiD

**Comment by rpottsoh** [comment]
I am going to move this to exercism/exercism.

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism #4554](https://github.com/exercism/exercism/issues/4554) via [**ZenHub**](https://www.zenhub.com/)
