### ISSUE TITLE
Intra-page links not working

### ISSUE THREAD

**Issue by DanCorder** [exercism/website-copy#669]
I think the correct place to raise this is probably the website project, but there's no Issues tab visible there.

Pages like https://exercism.io/tracks/kotlin/installation have links on them like https://exercism.io/tracks/kotlin/installation#macos (just under "Choose your operating system"). These links do not work as there is no anchor tag called \#macos on the page.

If you view the doc markdown file that contains the page information on github https://github.com/exercism/kotlin/blob/master/docs/INSTALLATION.md the links do work.

Presumably there is a problem converting the markdown to HTML for the main site.
Probably relatedly, the styling of the H1 tags on the website doesn't look right to me, but I guess that might be deliberate.

**Comment by F3PiX** [comment]
Hi @DanCorder ! Thanks for reporting. The right place to open an issue is https://github.com/exercism/exercism/issues. Could you copy it over please?

**Comment by DanCorder** [comment]
Thanks, moved to https://github.com/exercism/exercism/issues/4559
