### ISSUE TITLE
Please point me to issues that discuss uninstalling CLI

### ISSUE THREAD

**Issue by onlinematters** [exercism/website-copy#788]
I see in one entry about uninstalling cli that there are other issues that describe how to do that, but I can't find them.  Can you point me there or tell me how to uninstall the CLI?  The FAQs do not provide any discussion I can find.

**Comment by rpottsoh** [comment]
I think this issue would be better served at exercism/exercism/issues.  If you like I can move this issue there for you, or you may choose to close this issue and open another at [exercism/exercism/issues](https://github.com/exercism/exercism/issues)

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism #4705](https://github.com/exercism/exercism/issues/4705) via [**ZenHub**](https://www.zenhub.com/)
