### ISSUE TITLE
Please remove branches after they have been merged

### ISSUE THREAD

**Issue by rpottsoh** [exercism/website-copy#872]
What is happening is sometimes people are branching off of these branches (instead of master) in order to create their PR for their bio notes.  Which creates some difficulty later when it is time to merge.  A lot of the new mentors appear to be new to git and so it becomes difficult to work through this; the process of on-boarding their bio just became extra complicated.

To combat this it would be helpful that after a branch has served its purpose that it be deleted from this repo.  If you can do your work in a branch in a fork, that would be even more helpful.

I periodically have been removing branches that I find are no longer associated with a PR and I can see that their changes have been merged into master.

**Comment by sshine** [comment]
Do you mean branches on **exercism**/website-copy or branches on *contributor*/website-copy?

It should not be necessary to introduce new branches in exercism/website-copy for small changes.

**Comment by rpottsoh** [comment]
> Do you mean branches on exercism/website-copy or branches on contributor/website-copy?

exercism/website-copy.

> It should not be necessary to introduce new branches in exercism/website-copy for small changes.

I am not sure why there would be any need to create one ever.

**Comment by SleeplessByte** [comment]
As for this issue, I've been manually removing branches if people didn't, after merging.

> It should not be necessary to introduce new branches in exercism/website-copy for small changes.

It actually is. Fast-forwarding all on `master` doesn't work as well as you'd want. As soon as one small change is merged, the rest becomes outdated and would need to be:
- rebased
- updated
- something to move the head

With a branch from master, merging into that but than finally squash merging solves that issue.

**Comment by rpottsoh** [comment]
> As for this issue, I've been manually removing branches if people didn't, after merging.

This is what I have been doing as well, when I think to check.

This hasn't been a huge problem.  It was just an annoyance for a mentor when they were trying to add their bio information and had accidentally branched off another branch that existed in the repo when they forked and didn't realize that they didn't have master checked out.  I don't recall if the branch was left over from a PR or was still attached to an open PR.  At any rate had that branch been part of the PR opener's fork and not a branch on Exercism/website-copy the mentor would not have been able to do what they did.

**Comment by efx** [comment]
A repository admin can enable a setting to delete head branches after PR's have been merged:
https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by iHiD** [comment]
Closing and unpinning this as it happens automatically now :) Thanks for managing this.
