### ISSUE TITLE
Mentoring FAQ: add section about code fluency vs. stylistic preferences

### ISSUE THREAD

**Issue by pgaspar** [exercism/website-copy#913]
During today's Automated Mentoring Project discussion on Slack a few important things were brought up regarding the mentor's role in addressing stylistic issues, like sub-optional variable names:

![Screen Shot 2019-04-02 at 02 27 27](https://user-images.githubusercontent.com/31735/55369594-18b5df00-54ef-11e9-84f4-58a422268640.png)

I think we should add a section on the [Mentoring FAQ](https://github.com/exercism/website-copy/blob/master/pages/mentoring_faqs.md) explaining how a mentor should focus on fluency and how stylistic tweaks in general shouldn't be the sole reason to disapprove a submission.

I'm not submitting a PR because I was only made aware to this different perspective today. Maybe @iHiD or @kytrinyx have a better understanding of all the nuances to add that section.

**Comment by SleeplessByte** [comment]
Some of this is nicely written out in the "Our Values" page, some of it in Katrina's blog post(s). I agree that this should be communicated clearly to the mentors!

**Comment by iHiD** [comment]
Sorry I missed this. Maud has also been saying the same thing. Would
someone mind throwing up a skeleton pr for this and then I'll ping Katrina
and ask her to start to fill it out?
