### ISSUE TITLE
CLI token warning/hint

### ISSUE THREAD

**Issue by SaschaMann** [exercism/website-copy#930]
A lot of students ask for help with setting up the CLI on Gitter. Many of them also post their token as part of the command they're stuck at. @NobbZ is usally pretty fast at telling them to reset it and to not share it again, but it happens so often that perhaps there should be a hint on the website itself that the token is like a password and should not be shared.

The commit history of the walkthrough file makes me think that it's compiled with some tool and not edited directly in the HTML, is that correct? Otherwise I'll just add the hint myself, if it only requires editing the HTML.

There are also other places on the website where the token appears, but I can't find them in this repo.

**Comment by NobbZ** [comment]
The walkthrough which leads users through the installation is generated from this repository: https://github.com/exercism/interactive-cli-walkthrough

I'd also suggest to have a big red warning on https://exercism.io/my/settings, which clearly states that one should never tell anyone the token and that it is like a password.

**Comment by SaschaMann** [comment]
Making a big red warning that looks nice is beyond my HTML/CSS skills, so someone else would have to do that. However, I've added a PR to the walkthrough.

**Comment by SleeplessByte** [comment]
Since https://github.com/exercism/interactive-cli-walkthrough/pull/79 is merged, I assume this can be closed? If not, please re-open.

**Comment by SaschaMann** [comment]
@SleeplessByte The warning on the settings page is still missing:

> I'd also suggest to have a big red warning on https://exercism.io/my/settings, which clearly states that one should never tell anyone the token and that it is like a password.

**Comment by SleeplessByte** [comment]
Right. I don't _know_ if that is populated from this repository tho. Sounds like it needs to be in exercism/exercism ;)

**Comment by SaschaMann** [comment]
"Moved" it :)
