### ISSUE TITLE
Go-Analyzer comments

### ISSUE THREAD

**Issue by tehsphinx** [exercism/website-copy#948]
I added the comments to the `go-analyzer` repo in the `comments` branch and `/comments` folder. Feel free to move them to this repository whenever you are ready.

https://github.com/exercism/go-analyzer/tree/comments/comments

I used a directory structure that can be directly derived from the comment handle itself:
- `go.general.strings_trim_space_used` => `go/general/strings_trim_space_used.md`
- `go.two_fer.missing_share_with_function` => `go/two_fer/missing_share_with_function.md`
- `go.hamming.mixture_of_runes_and_bytes` => `go/hamming/mixture_of_runes_and_bytes.md`

**Comment by iHiD** [comment]
@tehsphinx Thanks!

- Could you remove the single bullet point syntax pls (e.g. [here](https://github.com/exercism/go-analyzer/blob/comments/comments/go/two_fer/extra_name_variable_created.md))
- Would you mind putting a WIP PR up (Just prefix the title with `[WIP]`) and we'll get some discussion going on that :) 

No rush on this.

Thanks!

**Comment by tehsphinx** [comment]
Closing in favour of the PR #1009
