### ISSUE TITLE
Python-Analyzer Comments

### ISSUE THREAD

**Issue by TreyAguirre** [exercism/website-copy#963]
I added the comments to the ```python-analyzer``` repo in the ```comments``` folder. Any feedback is welcome. 

https://github.com/exercism/python-analyzer/tree/master/comments

I followed the same structure as the Go and Ruby analyzers and made each comment an individual MD file. The Two Fer analyzer isn't using these files yet since I wanted to get feedback first. I will fix any issues with the comments and integrate them with the Two Fer analyzer so they can be moved to this repository later.

**Comment by angelikatyborska** [comment]
Looking at the current state of https://github.com/exercism/website-copy/tree/main/analyzer-comments/python/two-fer I conclude that this issue is already done (@BethanyG please reopen if I'm wrong)

**Comment by BethanyG** [comment]
@angelikatyborska  -- that is correct.  Those were added during the analyzer refactor #1.  😄   Thank you for reviewing and closing this!
