### ISSUE TITLE
Installing Python page links back to itself

### ISSUE THREAD

**Issue by jj-plane** [exercism/website-copy#993]
https://exercism.io/tracks/python/installation

This page has an unordered list at the bottom with more python resources. The top link is is a link to the current page. All it does is refresh the page.

**Comment by davearonson** [comment]
I looked at the Python, Ruby, and Elixir tracks, and at least on those three, that list appears on all the language-specific pages referenced in the list, and all have that same "problem".  Without delving into the actual code yet, I'd guess this likely happens on _all_ the languages.

So the question is, is this really a problem, and if so, what is the preferred solution?  Reasonable alternatives include omitting or de-linking the list item for the current page.

**Comment by angelikatyborska** [comment]
This was fixed in https://github.com/exercism/v2-website/pull/810
